---
language: go
go:
  - 1.9.x
script:
  - ./fmtpolice
  - go test -v ./...
notifications:
  email:
    recipients:
      - webteam@himalayaninstitute.org
    on_success: never
    on_failure: change
